### ISSUE TITLE
Overriding a loaded env

### ISSUE THREAD

**Issue by jwoertink** [gdotdesign/cr-dotenv#19]
Is there a way to override the ENV once it's loaded? 

```
#.env
DB_URL=postgres://localhost:5432/dev
```

```
#.env.test
DB_URL=postgres://localhost:5432/test
```

```crystal
require "dotenv"

Dotenv.load
Dotenv.load ".env.test"

puts ENV["DB_URL"]? #=> postgres://localhost:5432/dev
```

**Comment by j8r** [comment]
We want to have both possibilities: being able to override or not an already set key in `ENV`, this means adding an argument, for example `override : Bool = false` to all the existing 5 load methods, which is fine.

`Dotenv` could also be rethought as a struct, with an `override : Bool = false` as an instance variables.

**Comment by jwoertink** [comment]
Yeah. I can see not wanting to override those, but having a config option would be awesome. Or bring back the `load!` method to do it...
