### ISSUE TITLE
error with crystal 0.34

### ISSUE THREAD

**Issue by sachinbhutani** [gdotdesign/cr-dotenv#25]
I get this compile error with crystal 0.34

```
Unhandled exception: Parse error on line 2:5 (Dotenv::Parser::Error)
  from lib/dotenv/src/parser.cr:33:11 in 'parse'
  from lib/dotenv/src/dotenv.cr:24:5 in 'parse'
  from lib/dotenv/src/dotenv.cr:114:7 in 'load'
```

**Comment by j8r** [comment]
What is the INI file?

**Comment by j8r** [comment]
What is the original file?

**Comment by sachinbhutani** [comment]
here 
```
#your bot's token and user ID
token = obvious_fake_value
client = 12345678910
#the prefix to use
prefix = insultingly_long_prefix!
#your user ID
admin = 12345678910
#either 'prod' or 'dev'
runas = dev
```

**Comment by j8r** [comment]
This in an invalid dotenv file, there should have no spaces between the key name and the equal sign.

**Comment by j8r** [comment]
I don't know if spaces after the equal sign is valid. I see there is a test case for it in the [node version of dotenv](https://github.com/motdotla/dotenv/blob/master/tests/.env).

I will tend to say no, since it is not on shell interpreters.

**Comment by sachinbhutani** [comment]
thanks, it worked without spaces, but use to work with spaces too on crystal 0.33 or maybe older dotenv version (updated both together so can't say what broke it)

**Comment by j8r** [comment]
Yep, the parser has been entirely re-implemented from scratch.
The objective was to better adhere to the "dotenv specification".
Behaviors may differs then, like for your example.

Problem solved, the issue can be closed :slightly_smiling_face:

**Comment by sachinbhutani** [comment]
thanks!
