### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by vladfaust** [gdotdesign/cr-dotenv#8]
Please add [GitHub releases](https://github.com/gdotdesign/cr-dotenv/releases) regarding to https://github.com/crystal-lang/shards/issues/161.

**Comment by gdotdesign** [comment]
Released current state as [0.1.0](https://github.com/gdotdesign/cr-dotenv/releases/tag/0.1.0)

**Comment by vladfaust** [comment]
You have to tag your releases as `v0.1.0` because of
```
dotenv:
  github: gdotdesign/cr-dotenv
  version: ~> 0.1.0

git command failed: git ls-tree -r --full-tree --name-only v0.1.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

**Comment by gdotdesign** [comment]
I've changed it, let me know if it works.

**Comment by vladfaust** [comment]
It works, thank you!
